from configparser import ConfigParser
from oracledb import connect, Error, Connection, DatabaseError
from files.shared_defs import is_object, execute_sql, add_customer

import globals

def connect_to_oracle(config: ConfigParser, user: str, password: str) -> [object, str]:
    try:
        dsn = "{}:{}/{}".format(config.get('db', 'host'), config.get('db', 'port'), config.get('db', 'database'))
        conn = connect(user=user, password=password, dsn=dsn)
        conn.autocommit = True
        error = "OK"
    except Error as err:
        conn = None
        error = '\nError appeared: {}'.format(err)
    return [conn, error]

def cleanup_schema_oracle(conn: Connection, config: ConfigParser):
    app_user_group = globals.GAMES_APP_GROUP
    app_admin_group = globals.GAMES_ADMIN_GROUP
    app_schema = globals.GAMES_SCHEMA
    cur = conn.cursor()
    # Remove tables
    for table in ['customers', 'credit_cards', 'features', 'transactions', 'extras']:
        if is_object(cur, "SELECT COUNT(*) FROM user_tables WHERE table_name = '{}.{}'".format(app_schema, table)) == 1:
            cur.execute('DROP TABLE {}.{} CASCADE CONSTRAINTS'.format(app_schema, table))
    for user in config.get('settings', 'app_users').split(','):
        try:
            cur.execute('DROP USER {} CASCADE'.format(user))
        except DatabaseError as e:
            error, = e.args
            if error.code == 1918:
                pass
            else:
                print("Unknown error")
    try:
        cur.execute('DROP USER {} CASCADE'.format(app_schema))
    except DatabaseError as e:
        error, = e.args
        if error.code == 1918:
            pass
        else:
            print("Unknown error")


def deploy_schema_oracle(conn: Connection, config: ConfigParser):
    app_user_group = globals.GAMES_APP_GROUP
    app_admin_group = globals.GAMES_ADMIN_GROUP
    app_schema = globals.GAMES_SCHEMA
    cur = conn.cursor()
    # Create schema user
    cur.execute('CREATE USER {} IDENTIFIED BY accountwillbelocked'.format(app_schema))
        #cur.execute('REVOKE CREATE SESSION FROM {}'.format(app_schema))
    cur.execute('ALTER USER {} QUOTA UNLIMITED ON USERS'.format(app_schema))
    # Create application user
    for user in config.get('settings', 'app_users').split(','):
        cur.execute('CREATE USER {} IDENTIFIED BY "{}"'.format(user, config.get('settings', 'default_password')))
        cur.execute('GRANT CREATE SESSION TO {}'.format(user))
    # Create tables
    if is_object(cur, "SELECT COUNT(*) FROM user_tables WHERE table_name = '{}.customers'".format(app_schema)) == 0:
        #print("CREATE TABLE {}.customers (customer_id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY)".format(app_schema))
        sql = "CREATE TABLE {}.customers (customer_id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY," \
            "customer_fname varchar(50)," \
            "customer_lname varchar(50)," \
            "full_name varchar(100)," \
            "birthday date," \
            "citizen_id varchar(20)," \
            "birth_place varchar(50)," \
            "street varchar(50)," \
            "flat_number varchar(10)," \
            "city varchar(50)," \
            "zipcode varchar(10)," \
            "driving_license varchar(30)," \
            "passport_id varchar(30)," \
            "citizen_doc_id varchar(30)," \
            "mail varchar(50)," \
            "phone varchar(30)" \
            ")".format(app_schema)
        execute_sql(cur, sql)
        sql = ("CREATE TABLE {sch}.credit_cards (card_id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY, "
               "card_number varchar(30),"
               "card_validity varchar(12),"
               "customer_id NUMBER NOT NULL, "
               "CONSTRAINT fk_user FOREIGN KEY (customer_id) REFERENCES {sch}.customers(customer_id))").format(sch=app_schema)
        execute_sql(cur, sql)
        sql = ("CREATE TABLE {sch}.features (feature_id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,"
               "feature_name varchar(50),"
               "feature_price real)").format(sch=app_schema)
        execute_sql(cur, sql)
        prices = config.get('game_addons', 'feature_prices').split(',')
        i = 0
        for feature in config.get('game_addons', 'feature_descriptions').split(','):
            execute_sql(cur,
                        "INSERT INTO {}.features (feature_name, feature_price) VALUES ('{}', {})".format(
                            app_schema, feature, prices[i]))
            i += 1
        sql = ("CREATE TABLE {sch}.extras (extra_id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,"
               "extra_name varchar(50),"
               "extra_price real)").format(sch=app_schema)
        execute_sql(cur, sql)
        prices = config.get('game_addons', 'extra_prices').split(',')
        i = 0
        for feature in config.get('game_addons', 'extra_descriptions').split(','):
            execute_sql(cur,
                        "INSERT INTO {}.extras (extra_name, extra_price) VALUES ('{}', {})".format(app_schema, feature,
                                                                                                   prices[i]))
            i += 1
        sql = ("CREATE TABLE {sch}.transactions (trans_id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,"
               "feature_id NUMBER,"
               "extra_id NUMBER,"
               "price real,"
               "customer_id NUMBER NOT NULL,"
               "card_id NUMBER NOT NULL,"
               "transaction_time TIMESTAMP DEFAULT SYSDATE NOT NULL,"
               "CONSTRAINT fk_feature FOREIGN KEY (feature_id) REFERENCES {sch}.features(feature_id),"
               "CONSTRAINT fk_customer FOREIGN KEY (customer_id) REFERENCES {sch}.customers(customer_id),"
               "CONSTRAINT fk_card FOREIGN KEY (card_id) REFERENCES {sch}.credit_cards(card_id),"
               "CONSTRAINT fk_extra FOREIGN KEY (extra_id) REFERENCES {sch}.extras(extra_id))").format(sch=app_schema)
        execute_sql(cur, sql)
        for user in config.get('settings', 'app_users').split(','):
            for table in ['customers', 'credit_cards', 'features', 'transactions', 'extras']:
                execute_sql(cur, "GRANT SELECT, INSERT, UPDATE, DELETE ON {}.{} TO {}".format(app_schema, table, user))
        if is_object(cur, "SELECT COUNT(*) FROM {}.customers".format(app_schema)) < config.getint('settings',
                                                                                                  'minimal_customer_count'):
            global_domains = ['gmail.com', 'yahoo.com', 'hotmail.com', 'outlook.com', 'mail.com', 'live.com',
                              'icloud.com', 'aol.com', 'protonmail.com', 'zoho.com', 'yandex.com', 'gmx.com', 'me.com',
                              'msn.com', 'mail.ru', 'inbox.ru', 'bk.ru', 'list.ru', 'rediffmail.com', 'qq.com',
                              '126.com', '163.com', 'sina.com', 'yeah.net', 'rocketmail.com', 'fastmail.com',
                              'hushmail.com', 'tutanota.com', 'web.de', 'cox.net', 'comcast.net', 'btinternet.com',
                              'bellsouth.net', 'shaw.ca', 'blueyonder.co.uk', 'virginmedia.com', 'optonline.net',
                              'wanadoo.fr', 'orange.fr', 'seznam.cz']
            if config.get('settings', 'language') == 'pl_PL':
                polish_domains = ['wp.pl', 'onet.pl', 'o2.pl', 'interia.pl', 'gazeta.pl', 'tlen.pl', 'op.pl',
                                  'poczta.fm', 'autograf.pl', 'buziaczek.pl', 'vp.pl', 'go2.pl', 'home.pl',
                                  'prokonto.pl', 'neostrada.pl', 'amorki.pl', 'konto.pl', 'poczta.onet.pl', 'inetia.pl',
                                  'email.pl']
                global_domains.extend(polish_domains)
            for i in range(config.getint('settings', 'minimal_customer_count')):
                add_customer(config, cur, global_domains)
        cur.close()


